accounts/urls.py
#!/usr/bin/env python
from django.conf.urls import url
from accounts import user,role,permission

urlpatterns = [
    url('^login/$', user.login, name='login'),
    url('^logout/$', user.logout, name='logout'),
    url('^user/list/$', user.user_list, name='user-list'),
    url('^user/data/$', user.user_data, name='user-data'),
    url('^user/add/$',user.user_add,name='user-add'),
    url('^user/delete/$', user.user_delete, name='user-delete'),
    url('^user/editor/(\d*)', user.user_editor, name='user-editor'),
    url('^change/password/$', user.change_password, name='change-password'),

    url(r'^role/list/$', view=role.role_list, name='role-list'),
    url(r'^role/add/$', view=role.role_add, name='role-add'),
    url(r'^role/delete/$', view=role.role_delete, name='role-delete'),
    url(r'^role/editor/(\d*)$', view=role.role_editor, name='role-editor'),
    url(r'^role/data/$', view=role.role_data, name='role-data'),

    url(r'^permission/list/$', view=permission.permission_list, name='permission-list'),
    url(r'^permission/add/$', view=permission.permission_add, name='permission-add'),
    url(r'^permission/delete/$', view=permission.permission_delete, name='permission-delete'),
    url(r'^permission/editor/(\d*)$', view=permission.permission_editor, name='permission-editor'),
    url(r'^permission/data/$', view=permission.permission_data, name='permission-data'),
    url(r'^permission/deny/$',view=permission.permission_deny,name='permission-deny'),
]

assetdb/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.static import serve
from django.conf import settings
from assetdb.views import dashboard

urlpatterns = [
    url(r'^$',dashboard,name='index'),
    url(r'^admin/', admin.site.urls),
    #url(r'^tables/', include('datatables.urls',namespace='tables')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^nav/', include('navigation.urls', namespace='navigation')),
    url(r'^cmdb/', include('cmdb.urls', namespace='cmdb')),
    url(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT})
]

cmdb/urls.py
from django.conf.urls import url
from cmdb import contract
from cmdb.views import software, asset, idc, network, manufacturer, server, business

urlpatterns = [
    url(r'^asset/$', asset.asset, name='asset'),
    url(r'^asset/add/$', asset.asset_add, name='asset_add'),
    url(r'^asset/del/$', asset.asset_delete, name='asset_delete'),
    url(r'^asset/data/$', asset.asset_data, name='asset_data'),
    url(r'^collect/$', asset.asset_collect, name='asset_collect'),
    url(r'^idc/$', idc.idc, name='idc'),
    url(r'^idc/add/$', idc.idc_add, name='idc_add'),
    url(r'^idc/del/$', idc.idc_delete, name='idc_delete'),
    url(r'^idc/data/$', idc.idc_data, name='idc_data'),
    url(r'^server/$', server.server, name='server'),
    url(r'^server/add/$', server.server_add, name='server_add'),
    url(r'^server/del/$', server.server_delete, name='server_delete'),
    url(r'^server/data/$', server.server_data, name='server_data'),
    url(r'^network-device/$', network.network, name='network'),
    url(r'^network-device/add/$', network.network_add, name='network_add'),
    url(r'^network-device/del/$', network.network_delete, name='network_delete'),
    url(r'^network-device/data/$', network.network_data, name='network_data'),
    url(r'^software/$', software.software, name='software'),
    url(r'^software/add/$', software.software_add, name='software_add'),
    url(r'^software/del/$', software.software_delete, name='software_delete'),
    url(r'^software/data/$', software.software_data, name='software_data'),
    url(r'^manufacturer/$', manufacturer.manufacturer, name='manufacturer'),
    url(r'^manufacturer/add/$', manufacturer.manufacturer_add, name='manufacturer_add'),
    url(r'^manufacturer/del/$', manufacturer.manufacturer_delete, name='manufacturer_delete'),
    url(r'^manufacturer/data/$', manufacturer.manufacturer_data, name='manufacturer_data'),
    url(r'^business/$', business.business, name='business'),
    url(r'^business/add/$', business.business_add, name='business_add'),
    url(r'^business/del/$', business.business_delete, name='business_delete'),
    url(r'^business/data/$', business.business_data, name='business_data'),
    url(r'^contract/$', contract.contract, name='contract'),
    url(r'^contract/add/$', contract.contract_add, name='contract_add'),
    url(r'^contract/del/$', contract.contract_delete, name='contract_delete'),
    url(r'^contract/data/$', contract.contract_data, name='contract_data'),

    url(r'^asset/editor/(.*)$', asset.asset_editor, name='asset_editor'),
    url(r'^asset/details/(?P<sn>.*)$', asset.asset_details, name='asset_details'),
    url(r'^idc/editor/(.*)$', idc.idc_editor, name='idc_editor'),
    url(r'^server/editor/(.*)$', server.server_editor, name='server_editor'),
    url(r'^network-device/editor/(.*)$', network.network_editor, name='network_editor'),
    url(r'^software/editor/(.*)$', software.software_editor, name='software_editor'),
    url(r'^manufacturer/editor/(.*)$', manufacturer.manufacturer_editor, name='manufacturer_editor'),
    url(r'^business/editor/(.*)$', business.business_editor, name='business_editor'),
    url(r'^contract/editor/(.*)$', contract.contract_editor, name='contract_editor'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager,AbstractUser

def reset_user_image(instance, filename):
    end = filename.rsplit('.', 1)[1]
    return 'image/userImage/{}.{}'.format(instance.username, end)

class PermissionList(models.Model):
    """
        权限表
    """
    name = models.CharField('权限名称',max_length=64)
    url = models.CharField('URL',max_length=255)

    def __str__(self):
        return '%s(%s)' % (self.name, self.url)

    class Meta:
        verbose_name='权限管理'
        verbose_name_plural='权限管理'
        unique_together=('name','url')


class RoleList(models.Model):
    """
        角色表
    """
    name = models.CharField('角色名称',max_length=64,unique=True)
    permissions = models.ManyToManyField(PermissionList,verbose_name='权限', blank=True)

    def __str__(self):
        return self.name
    class Meta:
        verbose_name='角色管理'
        verbose_name_plural='角色管理'


class UserManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(email,
                                username=username,
                                password=password,
                                )

        user.is_active = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class UserInfo(AbstractBaseUser):
    """
        用户表
    """
    username = models.CharField('用户名',max_length=40, unique=True, db_index=True,
                                error_messages={'unique':'该用户名已经存在'})
    image=models.ImageField('图像',upload_to=reset_user_image,default='img/default_user.jpg')
    email = models.EmailField('邮箱',max_length=255,unique=True,
                              error_messages={'unique': '该邮箱已经存在'})
    is_active = models.BooleanField('状态',default=False)
    is_superuser = models.BooleanField('管理员',default=False)
    nickname = models.CharField('昵称',max_length=64, blank=True,null=True)
    role=models.ForeignKey('RoleList',verbose_name='角色',blank=True,null=True,on_delete=models.SET_NULL)
    objects = UserManager()
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def has_perm(self, perm, obj=None):
        if self.is_active and self.is_superuser:
            return True

    def has_module_perms(self, app_label):
        return True

    def get_all_permissions(self):
        return True

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_superuser

    class Meta:
        verbose_name='用户管理'
        verbose_name_plural='用户管理'

accounts/forms.py
#!/usr/bin/env python
from django import forms
from django.contrib import auth
from accounts.models import UserInfo,RoleList,PermissionList

class LoginUserForm(forms.Form):
    username = forms.CharField(label=u'账 号',
                               error_messages={'required': u'账号不能为空'},
                               widget=forms.TextInput(attrs={"class": "layui-input",
                                                             "lay-verify": "required",
                                                             "placeholder": "邮箱地址",
                                                             "autocomplete":"off",}))
    password = forms.CharField(label=u'密 码',
                               error_messages={'required': u'密码不能为空'},
                               widget=forms.PasswordInput(attrs={"class": "layui-input",
                                                                 "lay-verify": "required",
                                                                 "placeholder": "密码"}))
    url=forms.CharField(widget=forms.HiddenInput,required=False)

    def __init__(self, *args, **kwargs):
        self.user_cache = None
        super().__init__(*args, **kwargs)

    def clean_password(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            self.user_cache = auth.authenticate(username=username, password=password)
            if self.user_cache is None:
                raise forms.ValidationError(u'账号密码不匹配')
            elif not self.user_cache.is_active:
                raise forms.ValidationError(u'此账号已被禁用')
        return self.cleaned_data

    def get_user(self):
        return self.user_cache


class UserAddForm(forms.ModelForm):
    password2 = forms.CharField(label='重复密码', widget=forms.PasswordInput(attrs={"class": "form-control"}))

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request=request
        if not self.request.user.is_superuser:
            self.fields['is_superuser'].widget.attrs={'disabled':'disabled','class': 'form-control'}
        self.fields['username'].label = u'账 号'
        self.fields['username'].error_messages = {'required': u'请输入账号'}
        self.fields['email'].label = u'邮 箱'
        self.fields['email'].error_messages = {'required': u'请输入邮箱', 'invalid': u'请输入有效邮箱'}
        self.fields['nickname'].label = u'姓 名'
        self.fields['nickname'].error_messages = {'required': u'请输入姓名'}
        self.fields['is_active'].label = u'状 态'

    class Meta:
        model = UserInfo
        fields = ('username', 'email', 'password', 'password2', 'nickname', 'is_active','is_superuser')
        widgets = {
            'password': forms.PasswordInput(attrs={"class": "form-control"}),
            'username': forms.TextInput(attrs={"class": "form-control", 'autocomplete': 'off'}),
            'nickname': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off'}),
            'email': forms.EmailInput(attrs={"class": "form-control", 'autocomplete': 'off'}),
            'is_active': forms.Select(choices=((True, u'启用'), (False, u'禁用')),
                                      attrs={'class': 'form-control'}),
            'is_superuser':forms.Select(choices=((True, u'启用'), (False, u'禁用')),
                                         attrs={'class': 'form-control'}),
        }

    def _post_clean(self):
        pwd = self.cleaned_data.get('password')
        pwd2 = self.cleaned_data.get('password2')
        if pwd != pwd2:
            self.add_error('password', '两次密码不一致')
        return super()._post_clean()

    def save(self, commit=True):
        instance=super().save()
        if not self.request.user.is_superuser:
            if instance.is_superuser:
                instance.is_superuser=False
                instance.save()
        return instance


class UserEditForm(forms.ModelForm):

    class Meta:
        model = UserInfo
        fields = ['username', 'email', 'nickname', 'role', 'is_active', 'is_superuser']
        widgets = {
            'nickname': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off'}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'autocomplete': 'off'}),
            'is_active': forms.Select(choices=((True, u'启用'), (False, u'禁用')),
                                      attrs={'class': 'form-control'}),
            'role':forms.Select(attrs={'class': 'form-control'}),
            'is_superuser': forms.Select(choices=((True, u'启用'), (False, u'禁用')),
                                         attrs={'class': 'form-control'}),
        }

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request=request
        if not self.request.user.is_superuser:
            self.fields['is_superuser'].widget.attrs={'disabled':'disabled','class': 'form-control'}
        self.fields['username'].label = u'账 号'
        self.fields['username'].error_messages = {'required': u'请输入账号'}
        self.fields['email'].label = u'邮 箱'
        self.fields['email'].error_messages = {'required': u'请输入邮箱', 'invalid': u'请输入有效邮箱'}
        self.fields['nickname'].label = u'姓 名'
        self.fields['nickname'].error_messages = {'required': u'请输入姓名'}
        self.fields['is_active'].label = u'状 态'



    def save(self, commit=True):
        instance=super().save()
        if not self.request.user.is_superuser and instance.is_superuser:
            instance.is_superuser=False
            if commit:
                instance.save()
        return instance

class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(label=u'旧密码', error_messages={'required': '请输入旧密码'},
                                   widget=forms.PasswordInput(attrs={'class': 'form-control',}))
    new_password1 = forms.CharField(label=u'新密码', error_messages={'required': '请输入新密码'},
                                    widget=forms.PasswordInput(
                                        attrs={'class': 'form-control'}))
    new_password2 = forms.CharField(label=u'新密码', error_messages={'required': '请重复新输入密码'},
                                    widget=forms.PasswordInput(
                                        attrs={'class': 'form-control'}))


    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request=request
        super().__init__(*args, **kwargs)

    def clean_old_password(self):
        old_password = self.cleaned_data["old_password"]
        if not self.request.user.check_password(old_password):
            raise forms.ValidationError(u'旧密码错误')
        return old_password

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if len(password1)<6:
            raise forms.ValidationError(u'密码必须大于6位')

        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(u'两次密码输入不一致')
        return password2

    def save(self, commit=True):
        self.request.user.set_password(self.cleaned_data['new_password1'])
        if commit:
            self.request.user.save()
        return self.request.user


class RoleEditForm(forms.ModelForm):
    class Meta:
        model = RoleList
        fields = ['name', 'permissions']
        widgets = {
            'permissions': forms.SelectMultiple(attrs={'class': 'form-control', 'multiple': 'multiple'}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['permissions'].label = '可用 用户权限'


class RoleAddForm(forms.ModelForm):
    class Meta:
        model = RoleList
        fields = ['name', 'permissions']
        widgets = {
            'permissions': forms.SelectMultiple(attrs={'class': 'form-control', 'multiple': 'multiple'}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['permissions'].label = '权限'


class PermissionAddForm(forms.ModelForm):
    class Meta:
        model = PermissionList
        exclude = ('id',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off'}),
            'url': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': 'off'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].label = '权限名称'
        self.fields['url'].label = '链接地址'

accounts/views.py
from django.shortcuts import render

# Create your views here.

templates/accounts/change_password.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ html_title }}{% endblock %}
{% block content %}<div class="row">{% include 'form.html' %}</div>{% endblock %}
{% block script %}{% include 'form-js.html' %}{% endblock %}

templates/accounts/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'verdor/layui/css/layui.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <script>
        var login_url = "{% url 'accounts:login' %}"
    </script>
</head>
<body>
<div class="kit-login">
    <div class="kit-login-bg"></div>
    <div class="kit-login-wapper">
        <h2 class="kit-login-slogan">欢迎使用 <br> CMDB 后台管理系统</h2>
        <div class="kit-login-form">
            <h4 class="kit-login-title">登录</h4>
            <form class="layui-form">{% csrf_token %}
                {{ form.url }}
                <div class="kit-login-row">
                    <div class="kit-login-col">
                        <i class="layui-icon">&#xe612;</i>
                        <span class="kit-login-input">
                            {{ form.username }}
                        </span>
                    </div>
                    <div class="kit-login-col"></div>
                </div>
                <div class="kit-login-row">
                    <div class="kit-login-col">
                        <i class="layui-icon">&#xe64c;</i>
                        <span class="kit-login-input">
                            {{ form.password }}
                        </span>
                    </div>
                    <div class="kit-login-col"></div>
                </div>

                <div class="kit-login-row">
                    <button class="layui-btn kit-login-btn" lay-submit="submit" lay-filter="login_btn">登录</button>
                </div>
                <div class="kit-login-row" style="margin-bottom:0;">
                    <a href="javascript:;" style="color: rgb(153, 153, 153); text-decoration: none; font-size: 13px;"
                       id="forgot">忘记密码 ？</a>
                </div>
            </form>
        </div>
    </div>
</div>
<script src="{% static 'verdor/layui/layui.js' %}"></script>
<script>
    layui.use(['layer', 'form', 'element'], function () {
        var form = layui.form,
            $ = layui.jquery;
        $('#forgot').on('click', function () {
            layer.msg('请联系管理员.');
        });

        //监听提交
        form.on('submit(login_btn)', function (data) {
            var layIndex = layer.load(2, {
                shade: [0.1, '#393D49']
            });
            $.ajax({
                url: login_url,
                type: 'POST',
                dataType: 'json',
                data: data.field,
                success: function (data) {
                    if(typeof data==='object'){
                        console.log(data.URL);
                        alert('------------');
                        window.location.href=data.URL;
                    }
                    new_data = JSON.parse(data);
                    $.each(new_data, function (k, v) {
                        layer.msg(v[0].message);
                        return false;
                    });
                    layer.close(layIndex);
                },
                error: function (XMLHttpRequest, textStatus, errorThrown) {
                    layer.close(layIndex);
                    layer.msg('网络超时,请稍后重试...');
                }
            });
            return false;
        });
    });
</script>
</body>
</html>

templates/accounts/permission-add.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ html_title }}{% endblock %}
{% block content %}
    {% include 'form.html' %}
{% endblock %}
{% block script %}
    {% include 'form-js.html' %}
{% endblock %}

templates/accounts/permission-deny.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}权限不足|请联系管理员{% endblock %}
{% block content %}
    <div class="row"><div class="col-md-12 col-sm-12 col-xs-12">权限不足|请联系管理员</div></div>
{% endblock %}

templates/accounts/permission-editor.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ html_title }}{% endblock %}
{% block content %}
    {% include 'form.html' %}
{% endblock %}
{% block script %}
    {% include 'form-js.html' %}
{% endblock %}

templates/accounts/permission-list.html
{% extends 'base.html' %}
{% block title %}权限管理|{{ request.user }}{% endblock %}
{% block content %}{% include 'datatables/datatable.html' %}{% endblock %}
{% block script %}
    <script type="text/javascript">
        var DATA_URL = "{% url 'accounts:permission-data' %}";
        var DELETE_URL = "{% url 'accounts:permission-delete' %}";
        var COLS = [{{ kwargs.cols|safe }}];
        var ITABLE = '{{ kwargs.table_id }}';
        var MESSAGE = '{{ kwargs.message_str }}';
    </script>
    {% include 'datatables/create_datatables_js.html' %}
    {{ kwargs.script_bool }}
    <script type="text/html" id="toolbar-box">
        <div class="layui-btn-container">
            <button class="layui-btn layui-btn-sm" lay-event="DeleteData">删除选中数目</button>
            <a class="layui-btn layui-btn-sm" href="{% url 'accounts:permission-add' %}">添加</a>
        </div>
    </script>
    <script type="text/html" id='{{ kwargs.table_id|cut:"-tables" }}-toolbar'>
        <a class="layui-btn layui-btn-xs" href="{% url 'accounts:permission-editor' '' %}{% templatetag openvariable %}d.id{% templatetag closevariable %}">编辑</a>
        <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
    </script>
    <script type="text/javascript">
    </script>
{% endblock %}

templates/accounts/reset_password.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load nav_tags %}
{% block title %}重置密码{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            {% if messages %}
                {% for message in messages %}
                    <div class="{{ message.tags }}" role="alert">{{ message }}</div>
                {% endfor %}
            {% else %}
                <blockquote class="layui-elem-quote">重置密码</blockquote>
            {% endif %}
        </div>
        <div class="col-md-6 col-sm-12 col-xs-12">
            开发中...
        </div>
    </div>
{% endblock %}

templates/accounts/role-add.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ html_title }}{% endblock %}
{% block css_or_js %}
    <link rel="stylesheet" href="{% static 'verdor/bootstrap-duallistbox-master/bootstrap-duallistbox.min.css' %}">
{% endblock %}
{% block content %}
    {% include 'form.html' %}
{% endblock %}
{% block script %}
        <script rel="script" src="{% static 'verdor/bootstrap-duallistbox-master/jquery.bootstrap-duallistbox.min.js' %}"></script>
    {% include 'form-js.html' %}
    <script type="text/javascript">
        var editor_select = $('select[name="permissions"]').bootstrapDualListbox({
            nonSelectedListLabel: '可用 权限',
            selectedListLabel: '选中的 权限',
            preserveSelectionOnMove: 'moved',
            moveOnSelect: false
        });
    </script>
{% endblock %}

templates/accounts/role-editor.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ html_title }}{% endblock %}
{% block css_or_js %}
    <link rel="stylesheet" href="{% static 'verdor/bootstrap-duallistbox-master/bootstrap-duallistbox.min.css' %}">
{% endblock %}
{% block content %}
    {% include 'form.html' %}
{% endblock %}
{% block script %}
        <script rel="script" src="{% static 'verdor/bootstrap-duallistbox-master/jquery.bootstrap-duallistbox.min.js' %}"></script>
    {% include 'form-js.html' %}
    <script type="text/javascript">
        var editor_select = $('select[name="permissions"]').bootstrapDualListbox({
            nonSelectedListLabel: '可用 权限',
            selectedListLabel: '选中的 权限',
            preserveSelectionOnMove: 'moved',
            moveOnSelect: false
        });
    </script>
{% endblock %}

templates/accounts/role_list.html
{% extends 'base.html' %}
{% block title %}角色管理|{{ request.user }}{% endblock %}
{% block content %}{% include 'datatables/datatable.html' %}{% endblock %}
{% block script %}
    <script type="text/javascript">
        var DATA_URL = "{% url 'accounts:role-data' %}";
        var DELETE_URL = "{% url 'accounts:role-delete' %}";
        var COLS = [{{ kwargs.cols|safe }}];
        var ITABLE = '{{ kwargs.table_id }}';
        var MESSAGE = '{{ kwargs.message_str }}';
    </script>
    {% include 'datatables/create_datatables_js.html' %}
    {{ kwargs.script_bool }}
    <script type="text/html" id="toolbar-box">
        <div class="layui-btn-container">
            <button class="layui-btn layui-btn-sm" lay-event="DeleteData">删除选中数目</button>
            <a class="layui-btn layui-btn-sm" href="{% url 'accounts:role-add' %}">添加</a>
        </div>
    </script>
    <script type="text/html" id='{{ kwargs.table_id|cut:"-tables" }}-toolbar'>
        <a class="layui-btn layui-btn-xs" href="{% url 'accounts:role-editor' '' %}{% templatetag openvariable %}d.id{% templatetag closevariable %}">编辑</a>
        <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
    </script>
    <script type="text/javascript">
    </script>
{% endblock %}

templates/accounts/user-add.html
{% extends 'base.html' %}
{% block title %}{{ html_title }}{% endblock %}
{% block css_or_js %}
{% endblock %}
{% block content %}
    <div class="row">
        {% include 'form.html' %}
    </div>
{% endblock %}
{% block script %}
    {% include 'form-js.html' %}
{% endblock %}

templates/accounts/user-editor.html
{% extends 'base.html' %}
{% block title %}{{ html_url }}{% endblock %}
{% block css_or_js %}{% endblock %}
{% block content %}
    <div class="row">
        {% include 'form.html' %}
    </div>
{% endblock %}
{% include 'form-js.html' %}

templates/accounts/user_list.html
{% extends 'base.html' %}
{% block title %}用户管理|{{ request.user }}{% endblock %}
{% block content %}{% include 'datatables/datatable.html' %}{% endblock %}
{% block script %}
    <script type="text/javascript">
        var DATA_URL = "{% url 'accounts:user-data' %}";
        var DELETE_URL = "{% url 'accounts:user-delete' %}";
        var COLS = [{{ kwargs.cols|safe }}];
        var ITABLE = '{{ kwargs.table_id }}';
        var MESSAGE = '{{ kwargs.message_str }}';
    </script>
    {% include 'datatables/create_datatables_js.html' %}
    {{ kwargs.script_bool }}
    <script type="text/html" id="toolbar-box">
        <div class="layui-btn-container">
            <button class="layui-btn layui-btn-sm" lay-event="DeleteData">删除选中数目</button>
            <a class="layui-btn layui-btn-sm" href="{% url 'accounts:user-add' %}">添加</a>
        </div>
    </script>
    <script type="text/html" id='{{ kwargs.table_id|cut:"-tables" }}-toolbar'>
        <a class="layui-btn layui-btn-xs" href="{% url 'accounts:user-editor' '' %}{% templatetag openvariable %}d.id{% templatetag closevariable %}">编辑</a>
        <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
    </script>
    <script type="text/javascript">
    </script>
{% endblock %}