assetdb/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.static import serve
from django.conf import settings
from assetdb.views import dashboard

urlpatterns = [
    url(r'^$',dashboard,name='index'),
    url(r'^admin/', admin.site.urls),
    #url(r'^tables/', include('datatables.urls',namespace='tables')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^nav/', include('navigation.urls', namespace='navigation')),
    url(r'^cmdb/', include('cmdb.urls', namespace='cmdb')),
    url(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT})
]

cmdb/urls.py
from django.conf.urls import url
from cmdb import contract
from cmdb.views import software, asset, idc, network, manufacturer, server, business

urlpatterns = [
    url(r'^asset/$', asset.asset, name='asset'),
    url(r'^asset/add/$', asset.asset_add, name='asset_add'),
    url(r'^asset/del/$', asset.asset_delete, name='asset_delete'),
    url(r'^asset/data/$', asset.asset_data, name='asset_data'),
    url(r'^collect/$', asset.asset_collect, name='asset_collect'),
    url(r'^idc/$', idc.idc, name='idc'),
    url(r'^idc/add/$', idc.idc_add, name='idc_add'),
    url(r'^idc/del/$', idc.idc_delete, name='idc_delete'),
    url(r'^idc/data/$', idc.idc_data, name='idc_data'),
    url(r'^server/$', server.server, name='server'),
    url(r'^server/add/$', server.server_add, name='server_add'),
    url(r'^server/del/$', server.server_delete, name='server_delete'),
    url(r'^server/data/$', server.server_data, name='server_data'),
    url(r'^network-device/$', network.network, name='network'),
    url(r'^network-device/add/$', network.network_add, name='network_add'),
    url(r'^network-device/del/$', network.network_delete, name='network_delete'),
    url(r'^network-device/data/$', network.network_data, name='network_data'),
    url(r'^software/$', software.software, name='software'),
    url(r'^software/add/$', software.software_add, name='software_add'),
    url(r'^software/del/$', software.software_delete, name='software_delete'),
    url(r'^software/data/$', software.software_data, name='software_data'),
    url(r'^manufacturer/$', manufacturer.manufacturer, name='manufacturer'),
    url(r'^manufacturer/add/$', manufacturer.manufacturer_add, name='manufacturer_add'),
    url(r'^manufacturer/del/$', manufacturer.manufacturer_delete, name='manufacturer_delete'),
    url(r'^manufacturer/data/$', manufacturer.manufacturer_data, name='manufacturer_data'),
    url(r'^business/$', business.business, name='business'),
    url(r'^business/add/$', business.business_add, name='business_add'),
    url(r'^business/del/$', business.business_delete, name='business_delete'),
    url(r'^business/data/$', business.business_data, name='business_data'),
    url(r'^contract/$', contract.contract, name='contract'),
    url(r'^contract/add/$', contract.contract_add, name='contract_add'),
    url(r'^contract/del/$', contract.contract_delete, name='contract_delete'),
    url(r'^contract/data/$', contract.contract_data, name='contract_data'),

    url(r'^asset/editor/(.*)$', asset.asset_editor, name='asset_editor'),
    url(r'^asset/details/(?P<sn>.*)$', asset.asset_details, name='asset_details'),
    url(r'^idc/editor/(.*)$', idc.idc_editor, name='idc_editor'),
    url(r'^server/editor/(.*)$', server.server_editor, name='server_editor'),
    url(r'^network-device/editor/(.*)$', network.network_editor, name='network_editor'),
    url(r'^software/editor/(.*)$', software.software_editor, name='software_editor'),
    url(r'^manufacturer/editor/(.*)$', manufacturer.manufacturer_editor, name='manufacturer_editor'),
    url(r'^business/editor/(.*)$', business.business_editor, name='business_editor'),
    url(r'^contract/editor/(.*)$', contract.contract_editor, name='contract_editor'),
]

navigation/urls.py
from django.conf.urls import url
from navigation import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^list/', views.nav_list,name='nav-list'),
    url(r'^add/', views.nav_add, name='nav-add'),
    url(r'^editor/(\d*)', views.nav_editor, name='nav-editor'),
    url(r'^delete/', views.nav_delete, name='nav-delete'),
    url(r'^data/', views.nav_data,name='nav-data'),

]

navigation/models.py
from django.db import models


class NavStore(models.Model):
    name=models.CharField('名称',max_length=64)
    url=models.URLField('网址')
    remark=models.CharField('备注',max_length=200,blank=True,null=True)
    c_date=models.DateTimeField('创建时间',auto_now_add=True)

    def __str__(self):
        return '%s<%s>'%(self.name,self.url)

    class Meta:
        verbose_name='站点导航'
        verbose_name_plural='站点导航'
        unique_together=('name','url')

navigation/forms.py
from django import forms
from navigation.models import NavStore


class NavStoreForm(forms.ModelForm):
    class Meta:
        model=NavStore
        exclude=('c_date','id')
        widgets={
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'url':forms.URLInput(attrs={'class':'form-control'}),
            'remark':forms.TextInput(attrs={'class':'form-control'}),
        }

navigation/views.py
from django.shortcuts import render, redirect, reverse
from django.http import JsonResponse
from django.contrib.auth.views import login_required
from django.views.decorators.csrf import csrf_exempt
from accounts.permission import permission_verify
from datatables.utils import inittable

from navigation.datatable import NavTable
from navigation.models import NavStore
from navigation.forms import NavStoreForm


@login_required
@permission_verify
def index(request):
    html_title='站点导航'
    nav=NavStore.objects.all().values('name','url','remark')
    return render(request, 'navigation/index.html', locals())


@login_required
@permission_verify
def nav_list(request):
    kwargs = inittable(NavTable)
    return render(request, 'navigation/nav-list.html', locals())


@login_required
@permission_verify
def nav_add(request):
    if request.method == 'POST':
        JSON_RESULT = {'status': 200, 'message': '', 'error': '', 'data': []}
        forms = NavStoreForm(data=request.POST)
        if forms.is_valid():
            forms.save()
            JSON_RESULT['message'] = '添加成功'
            return JsonResponse(JSON_RESULT)
        JSON_RESULT['status'] = 201
        JSON_RESULT['error'] = forms.errors.as_json()
        return JsonResponse(JSON_RESULT)
    else:
        forms = NavStoreForm()
    html_title = '添加站点'
    cancel = reverse('navigation:nav-list')
    return render(request, 'navigation/nav-add.html', locals())


@login_required
@permission_verify
def nav_editor(request, data):
    try:
        nav = NavStore.objects.get(pk=data)
    except Exception:
        return redirect(reverse('accounts:user-add'))
    if request.method == 'POST':
        JSON_RESULT = {'status': 200, 'message': '', 'error': '', 'data': []}
        forms = NavStoreForm(data=request.POST, instance=nav)
        if forms.is_valid():
            forms.save()
            JSON_RESULT['message'] = '%s-更新成功' % forms.cleaned_data.get('name')
            return JsonResponse(JSON_RESULT)
        JSON_RESULT['status'] = 201
        JSON_RESULT['error'] = forms.errors.as_json()
        return JsonResponse(JSON_RESULT)
    else:
        forms = NavStoreForm(instance=nav)
    html_title = '更新站点'
    cancel = reverse('navigation:nav-list')
    return render(request, 'navigation/nav-editor.html', locals())


@login_required
@permission_verify
@csrf_exempt
def nav_delete(request):
    JSON_RESULT = {'status': 200, 'message': '', 'error': '', 'data': []}
    res = request.POST.getlist('id')
    count = NavStore.objects.filter(id__in=res).delete()
    if count[0] > 0:
        JSON_RESULT['message'] = '删除成功'
    else:
        JSON_RESULT['status'] = 201
        JSON_RESULT['error'] = '删除失败'
    return JsonResponse(JSON_RESULT)


@login_required
@permission_verify
def nav_data(request):
    table = NavTable(request)
    data = table.get_data()
    return JsonResponse(data)

templates/navigation/index.html
{% extends 'base.html' %}
{% block title %}{{ html_title }}{% endblock %}
{% block content %}
    {% if not nav %}
        <div class="col-md-12 col-sm-12 col-xs-12">
            <a href="{% url 'navigation:nav-add' %}">
                <span class="btn btn-default"><b>添加一个导航</b> <i class="fa fa-plus"></i></span>
            </a>
        </div>
    {% endif %}
    <div class="box-body">
        {% for n in nav %}
            <a href="{{ n.url }}" target="_blank">
                <div class="col-md-3">
                    <div class="box box-info">
                        <div class="box-header with-border">
                            <h3 class="box-title">{{ n.name }}</h3>
                        </div><!-- /.box-header -->
                        <div class="box-body">
                            {{ n.remark }}
                        </div><!-- /.box-body -->
                    </div><!-- /.box -->
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

templates/navigation/nav-add.html
{% extends 'base.html' %}
{% block title %}{{ html_title }}{% endblock %}
{% block content %}
    <div class="row">
        {% include 'form.html' %}
    </div>
{% endblock %}
{% block script %}
    {% include 'form-js.html' %}
{% endblock %}

templates/navigation/nav-editor.html
{% extends 'base.html' %}
{% block title %}{{ html_url }}{% endblock %}
{% block content %}
    <div class="row">
        {% include 'form.html' %}
    </div>
{% endblock %}
{% include 'form-js.html' %}

templates/navigation/nav-list.html
{% extends 'base.html' %}
{% block title %}导航窗口{% endblock %}
{% block content %}{% include 'datatables/datatable.html' %}{% endblock %}
{% block script %}
    <script type="text/javascript">
        var DATA_URL = "{% url 'navigation:nav-data' %}";
        var DELETE_URL = "{% url 'navigation:nav-delete' %}";
        var COLS = [{{ kwargs.cols|safe }}];
        var ITABLE = '{{ kwargs.table_id }}';
        var MESSAGE = '{{ kwargs.message_str }}';
    </script>
    {% include 'datatables/create_datatables_js.html' %}
    {{ kwargs.script_bool }}
    <script type="text/html" id="toolbar-box">
        <div class="layui-btn-container">
            <button class="layui-btn layui-btn-sm" lay-event="DeleteData">删除选中数目</button>
            <a class="layui-btn layui-btn-sm" href="{% url 'navigation:nav-add' %}">添加</a>
        </div>
    </script>
    <script type="text/html" id='{{ kwargs.table_id|cut:"-tables" }}-toolbar'>
        <a class="layui-btn layui-btn-xs" href="{% url 'navigation:nav-editor' '' %}{% templatetag openvariable %}d.id{% templatetag closevariable %}">编辑</a>
        <a class="layui-btn layui-btn-danger layui-btn-xs" lay-event="del">删除</a>
    </script>
    <script type="text/javascript">
    </script>
{% endblock %}