accounts/urls.py
#!/usr/bin/env python
from django.conf.urls import url
from accounts import user,role,permission

urlpatterns = [
    url('^login/$', user.login, name='login'),
    url('^logout/$', user.logout, name='logout'),
    url('^user/list/$', user.user_list, name='user-list'),
    url('^user/data/$', user.user_data, name='user-data'),
    url('^user/add/$',user.user_add,name='user-add'),
    url('^user/delete/$', user.user_delete, name='user-delete'),
    url('^user/editor/(\d*)', user.user_editor, name='user-editor'),
    url('^change/password/$', user.change_password, name='change-password'),

    url(r'^role/list/$', view=role.role_list, name='role-list'),
    url(r'^role/add/$', view=role.role_add, name='role-add'),
    url(r'^role/delete/$', view=role.role_delete, name='role-delete'),
    url(r'^role/editor/(\d*)$', view=role.role_editor, name='role-editor'),
    url(r'^role/data/$', view=role.role_data, name='role-data'),

    url(r'^permission/list/$', view=permission.permission_list, name='permission-list'),
    url(r'^permission/add/$', view=permission.permission_add, name='permission-add'),
    url(r'^permission/delete/$', view=permission.permission_delete, name='permission-delete'),
    url(r'^permission/editor/(\d*)$', view=permission.permission_editor, name='permission-editor'),
    url(r'^permission/data/$', view=permission.permission_data, name='permission-data'),
    url(r'^permission/deny/$',view=permission.permission_deny,name='permission-deny'),
]

assetdb/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.static import serve
from django.conf import settings
from assetdb.views import dashboard

urlpatterns = [
    url(r'^$',dashboard,name='index'),
    url(r'^admin/', admin.site.urls),
    #url(r'^tables/', include('datatables.urls',namespace='tables')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^nav/', include('navigation.urls', namespace='navigation')),
    url(r'^cmdb/', include('cmdb.urls', namespace='cmdb')),
    url(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT})
]

cmdb/urls.py
from django.conf.urls import url
from cmdb import contract
from cmdb.views import software, asset, idc, network, manufacturer, server, business

urlpatterns = [
    url(r'^asset/$', asset.asset, name='asset'),
    url(r'^asset/add/$', asset.asset_add, name='asset_add'),
    url(r'^asset/del/$', asset.asset_delete, name='asset_delete'),
    url(r'^asset/data/$', asset.asset_data, name='asset_data'),
    url(r'^collect/$', asset.asset_collect, name='asset_collect'),
    url(r'^idc/$', idc.idc, name='idc'),
    url(r'^idc/add/$', idc.idc_add, name='idc_add'),
    url(r'^idc/del/$', idc.idc_delete, name='idc_delete'),
    url(r'^idc/data/$', idc.idc_data, name='idc_data'),
    url(r'^server/$', server.server, name='server'),
    url(r'^server/add/$', server.server_add, name='server_add'),
    url(r'^server/del/$', server.server_delete, name='server_delete'),
    url(r'^server/data/$', server.server_data, name='server_data'),
    url(r'^network-device/$', network.network, name='network'),
    url(r'^network-device/add/$', network.network_add, name='network_add'),
    url(r'^network-device/del/$', network.network_delete, name='network_delete'),
    url(r'^network-device/data/$', network.network_data, name='network_data'),
    url(r'^software/$', software.software, name='software'),
    url(r'^software/add/$', software.software_add, name='software_add'),
    url(r'^software/del/$', software.software_delete, name='software_delete'),
    url(r'^software/data/$', software.software_data, name='software_data'),
    url(r'^manufacturer/$', manufacturer.manufacturer, name='manufacturer'),
    url(r'^manufacturer/add/$', manufacturer.manufacturer_add, name='manufacturer_add'),
    url(r'^manufacturer/del/$', manufacturer.manufacturer_delete, name='manufacturer_delete'),
    url(r'^manufacturer/data/$', manufacturer.manufacturer_data, name='manufacturer_data'),
    url(r'^business/$', business.business, name='business'),
    url(r'^business/add/$', business.business_add, name='business_add'),
    url(r'^business/del/$', business.business_delete, name='business_delete'),
    url(r'^business/data/$', business.business_data, name='business_data'),
    url(r'^contract/$', contract.contract, name='contract'),
    url(r'^contract/add/$', contract.contract_add, name='contract_add'),
    url(r'^contract/del/$', contract.contract_delete, name='contract_delete'),
    url(r'^contract/data/$', contract.contract_data, name='contract_data'),

    url(r'^asset/editor/(.*)$', asset.asset_editor, name='asset_editor'),
    url(r'^asset/details/(?P<sn>.*)$', asset.asset_details, name='asset_details'),
    url(r'^idc/editor/(.*)$', idc.idc_editor, name='idc_editor'),
    url(r'^server/editor/(.*)$', server.server_editor, name='server_editor'),
    url(r'^network-device/editor/(.*)$', network.network_editor, name='network_editor'),
    url(r'^software/editor/(.*)$', software.software_editor, name='software_editor'),
    url(r'^manufacturer/editor/(.*)$', manufacturer.manufacturer_editor, name='manufacturer_editor'),
    url(r'^business/editor/(.*)$', business.business_editor, name='business_editor'),
    url(r'^contract/editor/(.*)$', contract.contract_editor, name='contract_editor'),
]

navigation/urls.py
from django.conf.urls import url
from navigation import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^list/', views.nav_list,name='nav-list'),
    url(r'^add/', views.nav_add, name='nav-add'),
    url(r'^editor/(\d*)', views.nav_editor, name='nav-editor'),
    url(r'^delete/', views.nav_delete, name='nav-delete'),
    url(r'^data/', views.nav_data,name='nav-data'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-ch">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    {% include 'link.html' %}
    {% block css_or_js %}{% endblock %}
</head>
<body class="hold-transitiheader-js.htmlon skin-blue sidebar-mini">
<div class="wrapper">
    <!-- Main Header -->
    <header class="main-header">
        <!-- Logo -->
        <a href="/" class="logo">
            <span class="logo-mini"><b>A</b>LT</span>
            <span class="logo-lg"><b>Admin</b>LTE</span>
        </a>
        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            {% if header_temp %}{% include header_temp %}{% endif %}
            <!-- Navbar Right Menu -->
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <!-- Notifications Menu -->
                    <li class="dropdown notifications-menu">
                        <!-- Menu toggle button -->
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bell-o"></i>
                            <span class="label label-warning">10</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="header">You have 10 notifications</li>
                            <li>
                                <!-- Inner Menu: contains the notifications -->
                                <ul class="menu">
                                    <li><!-- start notification -->
                                        <a href="#">
                                            <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                        </a>
                                    </li>
                                    <!-- end notification -->
                                </ul>
                            </li>
                            <li class="footer"><a href="#">View all</a></li>
                        </ul>
                    </li>

                    <li class="dropdown user user-menu">
                        <!-- Menu Toggle Button -->
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{{ MEDIA_URL }}{{ request.user.image }}" class="user-image" alt="User Image">
                            <span class="hidden-xs">{{ request.user }}</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- The user image in the menu -->
                            <li class="user-header">
                                <img src="{{ MEDIA_URL }}{{ request.user.image }}" class="img-circle" alt="User Image">
                                <p>{{ request.user.email }}</p>
                            </li>
                            <!-- Menu Body
                            <li class="user-body">
                                <div class="row">
                                    <div class="col-xs-4 text-center">
                                        <a href="#"></a>
                                    </div>
                                </div>
                            </li> -->
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="{% url 'accounts:change-password' %}"
                                       class="btn btn-default btn-flat">修改密码</a>
                                </div>
                                <div class="pull-right">
                                    <a href="{% url 'accounts:logout' %}" class="btn btn-default btn-flat">注销</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <!-- Control Sidebar Toggle Button -->
                    <li>

                        <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
        {% include 'sidebar.html' %}
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content container-fluid">{% block content %}{% endblock %}</section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <!-- Main Footer -->
    <footer class="main-footer">
        <!-- To the right -->
        <div class="pull-right hidden-xs">
            Anything you want
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; 2016 <a href="#">Company</a>.</strong> All rights reserved.
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Create the tabs -->
        <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
            <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
            <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <!-- Home tab content -->
            <div class="tab-pane active" id="control-sidebar-home-tab">
                <h3 class="control-sidebar-heading">Recent Activity</h3>
                <ul class="control-sidebar-menu">
                    <li>
                        <a href="javascript:;">
                            <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                            <div class="menu-info">
                                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                                <p>Will be 23 on April 24th</p>
                            </div>
                        </a>
                    </li>
                </ul>
                <!-- /.control-sidebar-menu -->

                <h3 class="control-sidebar-heading">Tasks Progress</h3>
                <ul class="control-sidebar-menu">
                    <li>
                        <a href="javascript:;">
                            <h4 class="control-sidebar-subheading">
                                Custom Template Design
                                <span class="pull-right-container">
                    <span class="label label-danger pull-right">70%</span>
                  </span>
                            </h4>

                            <div class="progress progress-xxs">
                                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                            </div>
                        </a>
                    </li>
                </ul>
                <!-- /.control-sidebar-menu -->

            </div>
            <!-- /.tab-pane -->
            <!-- Stats tab content -->
            <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
            <!-- /.tab-pane -->
            <!-- Settings tab content -->
            <div class="tab-pane" id="control-sidebar-settings-tab">
                <form method="post">
                    <h3 class="control-sidebar-heading">General Settings</h3>

                    <div class="form-group">
                        <label class="control-sidebar-subheading">
                            Report panel usage
                            <input type="checkbox" class="pull-right" checked>
                        </label>

                        <p>
                            Some information about this general settings option
                        </p>
                    </div>
                    <!-- /.form-group -->
                </form>
            </div>
            <!-- /.tab-pane -->
        </div>
    </aside>
    <div class="control-sidebar-bg">111</div>
</div>

<!-- ./wrapper -->
{% include 'botton-js.html' %}
{% block script %}{% endblock %}
</body>
</html>

templates/botton-js.html
{% load staticfiles %}
<script src="{% static 'verdor/jquery-1.11.3/jquery.min.js' %}"></script>
<!-- REQUIRED JS SCRIPTS -->
<script src="{% static 'verdor/layui/layui.js' %}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'verdor/adminLTE/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'verdor/adminLTE/dist/js/adminlte.min.js' %}"></script>

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title %}仪表盘{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-solid">
                <div class="box-header">
                    <i class="fa fa-bar-chart-o"></i>
                    <h3 class="box-title">设备状态
                        <small>(%)</small>
                    </h3>
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-default btn-sm" data-widget="collapse"><i
                                class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-default btn-sm" data-widget="remove"><i
                                class="fa fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-xs-6 col-md-2 col-md-offset-1 text-center">
                            <input type="text" class="knob" value="{{ on_rate }}" data-width="90" data-height="90"
                                   data-fgColor="#00a65a" data-readonly="true" title="在线">
                            <div class="knob-label">在线</div>
                        </div>
                        <!-- ./col -->
                        <div class="col-xs-6 col-md-2 text-center">
                            <input type="text" class="knob" value="{{ no_rate }}" data-width="90" data-height="90"
                                   data-fgColor="#f56954" data-readonly="true" title="下线">
                            <div class="knob-label">下线</div>
                        </div>
                        <!-- ./col -->

                        <div class="col-xs-6 col-md-2 text-center">
                            <input type="text" class="knob" value="{{ bd_rate }}" data-width="90" data-height="90"
                                   data-fgColor="#932ab6" data-readonly="true" title="故障">
                            <div class="knob-label">故障</div>
                        </div>
                        <!-- ./col -->
                        <div class="col-xs-6 col-md-2 text-center">
                            <input type="text" class="knob" value="{{ bu_rate }}" data-width="90" data-height="90"
                                   data-fgColor="#3c8dbc" data-readonly="true" title="备用">
                            <div class="knob-label">备用</div>
                        </div>
                        <!-- ./col -->
                        <div class="col-xs-6 col-md-2 text-center">
                            <input type="text" class="knob" value="{{ un_rate }}" data-width="90" data-height="90"
                                   data-fgColor="#cccccc" data-readonly="true" title="未知">
                            <div class="knob-label">未知</div>
                        </div>
                        <!-- ./col -->
                    </div>
                    <!-- /.row -->
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="box box-solid">
                <div class="box-header">
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-default btn-sm" data-widget="collapse"><i
                                class="fa fa-minus"></i>
                        </button>
                        <button type="button" class="btn btn-default btn-sm" data-widget="remove"><i
                                class="fa fa-times"></i>
                        </button>
                    </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-6">
                            <div id="status-count" style="height:450px"></div>
                        </div>
                        <div class="col-md-6">
                            <div id="server-count" style="height:450px"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-xs-12">

        </div>
    </div>
{% endblock %}
{% block script %}
    <script type="text/javascript" src="{% static 'verdor/Knob/jquery.knob.js' %}"></script>
    <script type="text/javascript" src="{% static 'verdor/echarts/echarts.min.js' %}"></script>
    <script type="text/javascript">
        var x_status ={{ xAxis|safe }};
        var y_status ={{ yAxis|safe }};
        var x_server ={{ server_xAxis|safe }};
        var y_server ={{ server_yAxis|safe }};
    </script>
    <script type="text/javascript">
        layui.use('layer', function () {
            var layer = layui.layer;
            var loading = layer.load(2, {
                shade: [0.4, '#393D49']
            });
            $(".knob").knob({
                draw: function () {
                    // "tron" case
                    if (this.$.data('skin') == 'tron') {
                        var a = this.angle(this.cv)  // Angle
                            , sa = this.startAngle          // Previous start angle
                            , sat = this.startAngle         // Start angle
                            , ea                            // Previous end angle
                            , eat = sat + a                 // End angle
                            , r = true;

                        this.g.lineWidth = this.lineWidth;
                        this.o.cursor
                        && (sat = eat - 0.3)
                        && (eat = eat + 0.3);
                        if (this.o.displayPrevious) {
                            ea = this.startAngle + this.angle(this.value);
                            this.o.cursor
                            && (sa = ea - 0.3)
                            && (ea = ea + 0.3);
                            this.g.beginPath();
                            this.g.strokeStyle = this.previousColor;
                            this.g.arc(this.xy, this.xy, this.radius - this.lineWidth, sa, ea, false);
                            this.g.stroke();
                        }

                        this.g.beginPath();
                        this.g.strokeStyle = r ? this.o.fgColor : this.fgColor;
                        this.g.arc(this.xy, this.xy, this.radius - this.lineWidth, sat, eat, false);
                        this.g.stroke();

                        this.g.lineWidth = 2;
                        this.g.beginPath();
                        this.g.strokeStyle = this.o.fgColor;
                        this.g.arc(this.xy, this.xy, this.radius - this.lineWidth + 1 + this.lineWidth * 2 / 3, 0, 2 * Math.PI, false);
                        this.g.stroke();
                        return false;
                    }
                }
            });
            var StatusCountChart = echarts.init(document.getElementById('status-count'));
            var ServiceCountChart = echarts.init(document.getElementById('server-count'));
            var status_option = {
                color: ['#3398DB'],
                title: {
                    text: '各状态资产数量统计'
                },
                tooltip: {},
                legend: {
                    data: ['数量']
                },
                xAxis: {
                    data: ['在线', '下线', '故障', '备用', '未知']
                },
                yAxis: {},
                series: [{
                    name: '数量',
                    type: 'bar',
                    data: y_status
                }]
            };
            var server_option = {
                title: {
                    text: '各类型资产数量统计',
                    subtext: '纯属虚构',
                    x: 'center'
                },
                tooltip: {
                    trigger: 'item',
                    formatter: "{a} <br/>{b} : {c} ({d}%)"
                },
                legend: {
                    orient: 'vertical',
                    left: 'left',
                    data: ['服务器','网络设备','存储设备','安全设备','付费软件/系统']
                },
                series: [
                    {
                        type: 'pie',
                        radius: '55%',
                        center: ['50%', '60%'],
                        data: y_server,
                        itemStyle: {
                            emphasis: {
                                shadowBlur: 10,
                                shadowOffsetX: 0,
                                shadowColor: 'rgba(0, 0, 0, 0.5)'
                            }
                        }
                    }
                ]
            };
            StatusCountChart.setOption(status_option);
            ServiceCountChart.setOption(server_option);
            layer.close(loading);
        });
        /*
        var inp=$('#qwq');
        var int=window.setInterval("task()",100);
        function task() {
            value=parseInt(inp.val());
            inp.val(value+1)
        }*/

    </script>
{% endblock %}

templates/form-js.html
<script type="text/javascript">
        CustomFormPost = function (url) {
            var URL=window.location.href;
            if(url){
                URL=url;
            }
            layui.use('layer', function () {
                var layer = layui.layer;
                $('form').submit(function () {
                    var layIndex = layer.load(2, {
                        shade: [0.1, '#393D49']
                    });
                    data = $(this).serialize();
                    $.ajax({
                        type: 'POST'
                        , url: URL
                        , data: data
                        , dataType: 'json'
                        , success: function (data) {
                            if (data.status == 200) {
                                layer.msg(data.message)
                            }
                            else {
                                error = JSON.parse(data.error);
                                console.log(data);
                                console.log(error);
                                $.each(error, function (k, v) {
                                    msg = v[0].message;
                                    if(k==='__all__'){
                                        layer.msg(msg);
                                        return false
                                    }
                                    $this = $("div[data-error='" + k + "']");
                                    $this.text(msg);
                                    $this.parent().addClass('has-error')
                                })
                            }
                            layer.close(layIndex);
                        }
                        , error: function (XMLHttpRequest, textStatus, errorThrown) {
                            layer.close(layIndex);
                            layer.msg('网络超时,请稍后重试...');
                        }
                    });
                    return false
                });
                $('input').on('focus', function () {
                    k = $(this).attr('name');
                    $this = $("div[data-error='" + k + "']");
                    $this.text('');
                    $this.parent().removeClass('has-error')
                })
            })
        };
        CustomFormPost()
    </script>

templates/form.html
<div class="col-md-12 col-sm-12 col-xs-12">
    <blockquote class="layui-elem-quote">{{ html_title }}</blockquote>
</div>
<div class="col-md-10 col-sm-12 col-xs-12">
    <form class="form-horizontal">
        {% csrf_token %}
        {% for form in forms %}
            <div class="form-group">
                <label for="{{ form.id_for_label }}" class="col-md-1 {% if form.field.required %}control-label{% else %}control-label unrequired{% endif %}">{{ form.label }}</label>
                <div class="{% if col_md %}{{ col_md }}{% else %}col-md-3{% endif %}">
                    {{ form }}
                </div>
                <div class="col-md-2 input-error" data-error="{{ form.name }}"></div>
            </div>
        {% endfor %}
        <div class="form-group">
            <div class="col-md-offset-1 col-md-2 col-sm-2 col-xs-2">
                <input class="btn btn-primary" type="submit" value="提交">
            </div>
            <div class="col-md-2 col-sm-2 col-xs-2">
                <a href="{{ cancel }}" class="btn btn-primary">取消</a>
            </div>
        </div>
    </form>
</div>

templates/header.html
<div class="collapse navbar-collapse pull-left" id="navbar-collapse">
    <ul class="nav navbar-nav">
        <li id="server"><a href="{% url 'cmdb:server' %}"><b>服务器管理</b></a></li>
        <li id="idc"><a href="{% url 'cmdb:idc' %}"><b>机房管理</b></a></li>
        <li id="network"><a href="{% url 'cmdb:network' %}"><b>网络设备管理</b></a></li>
        <li id="business"><a href="{% url 'cmdb:business' %}"><b>业务线</b></a></li>
        <li id="software"><a href="{% url 'cmdb:software' %}"><b>软件/系统</b></a></li>
        <li id="contract"><a href="{% url 'cmdb:contract' %}"><b>合同</b></a></li>
        <li id="manufacturer"><a href="{% url 'cmdb:manufacturer' %}"><b>厂商</b></a></li>
    </ul>
</div>

templates/index.html
{% extends 'base.html' %}

templates/sidebar.html
{% load staticfiles %}
<section class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel">
        <div class="pull-left image">
            <img src="{{ MEDIA_URL }}{{ request.user.image }}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
            <p>{{ request.user }}</p>
            <!-- Status -->
            <a href="#"><i class="fa fa-circle text-success"></i> 在线</a>
        </div>
    </div>
    <!-- Sidebar Menu -->

    <ul class="sidebar-menu" data-widget="tree">
        <li class="header"><span>导航窗口</span></li>
        <!-- Optionally, you can add icons to the links -->
        <li id="index">
            <a href="{% url 'index' %}"><i class="fa fa fa-dashboard"></i> <span>仪表盘</span></a>
        </li>
        <li class="treeview" id="nav">
            <a href="javascript:;"><i class="fa fa-align-justify"></i> <span>站点导航</span>
                <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
            </a>
            <ul class="treeview-menu">
                <li id="nav-index"><a href="{% url 'navigation:index' %}">站点导航</a></li>
                <li id="nav-list"><a href="{% url 'navigation:nav-list' %}">管理站点</a></li>
            </ul>
        </li>
        <li class="treeview" id="cmdb">
            <a href="javascript:;"><i class="fa fa-database"></i> <span>资产管理</span>
                <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
            </a>
            <ul class="treeview-menu">
                <li id="asset"><a href="{% url 'cmdb:asset' %}">资产总表</a></li>
                <li id="server"><a href="{% url 'cmdb:server' %}">主机管理</a></li>
{#                <li id="idc"><a href="{% url 'cmdb:idc' %}">机房管理</a></li>#}
                <li><a href="#">机柜管理</a></li>
            </ul>
        </li>
        <li class="treeview" id="accounts">
            <a href="javascript:;"><i class="fa fa-users"></i>
                <span>用户管理</span>
                <span class="pull-right-container"><i class="fa fa-angle-left pull-right"></i></span>
            </a>
            <ul class="treeview-menu">
                <li id="user"><a href="{% url 'accounts:user-list' %}">用户管理</a></li>
                <li id="role"><a href="{% url 'accounts:role-list' %}">角色管理</a></li>
                <li id="permission"><a href="{% url 'accounts:permission-list' %}">权限管理</a></li>
            </ul>
        </li>
    </ul>
    <!-- /.sidebar-menu -->
    <script>
        pathname=window.location.pathname;
        name_list=pathname.split('/');
        var page=document.getElementById(name_list[1]);
        if(pathname==='/'){
            document.getElementById('index').className='active'
        }
        if(name_list[1]==='nav'){
            page.className+=' active';
            if(name_list[2]){
                document.getElementById('nav-list').className='active';
            }
            else{
                document.getElementById('nav-index').className='active';
            }
        }
        else if(name_list[3] === 'deny'){}
        else if(name_list[1] === 'cmdb'){
            page.className+=' active';
            document.getElementById(name_list[2]).className='active'
        }
        else if(name_list[1] === 'accounts'){
            page.className+=' active';
            document.getElementById(name_list[2]).className='active'
        }


    </script>
</section>